#pragma once

#define MACRO_EPS (10e-308)
#define MACRO_RND_SEED 123456

//Initialize
#define MACRO_NMAX 500
#define MACRO_MAX  200

#define MACRO_FOODSOURCE 10
//#define FOODSOURCE 60
#define MACRO_NUM_FOODS 2
//#define MACRO_FOOD_DIST 45
//#define MACRO_FOOD_ANGLE 80

#define MACRO_NEST_X (MACRO_MAX/2)
#define MACRO_NEST_Y (MACRO_MAX/3)

#define MACRO_CART_X_ZERO MACRO_NEST_X
#define MACRO_CART_Y_ZERO MACRO_NEST_Y


//Caluculation
#define MACRO_REC 0.4
//#define MACRO_REC 0.3
#define MACRO_EVAPOLATION_CONST 0.01
#define MACRO_MAX_SEARCH_TIME 150
#define MACRO_MAX_STEP 100
#define MACRO_MAX_TIME 40000
#define MACRO_OFFSET_TIME 0
#define MACRO_EMI 0.08
#define MACRO_ENEST 1.0
#define MACRO_HIL_CONST 50.0
#define MACRO_UNIT 2.0
#define MACRO_DIFFE 0.015

